### PR TITLE
Fix card width in extra small devices

### PR DESCRIPTION
**Pull request by oxavibes**
I just added a media query so those ".gallery" styles will be only applied starting from 768px

### CODE REVIEW

**Comment by JacksonBates** [comment]
Hey @oxavibes were you intending to have this qualify for Hacktoberfest?

This issue was designed to help people make their first Hacktoberfest PR - it's about 8hrs early to count for Hacktoberfest!

If you'd like it to count, close the PR and reopen it tomorrow :)

**Comment by JacksonBates** [comment]
@oxavibes sign up here if you haven't already: https://hacktoberfest.digitalocean.com/

**Comment by oxavibes** [comment]
Yes I did, I just wanted to warm up 😅

**Comment by JacksonBates** [comment]
Just an FYI, which you probably realised already - it wasn't 8hrs early, it was two days early :)

**Comment by oxavibes** [comment]
Haha yes I am aware 😄, this was my first pull request and I wanted to make a test before the event so I could become familiar with the process

**Comment by JacksonBates** [comment]
@oxavibes when you re-opened your PR, did it get registered on your Hacktoberfest counter? Check and let me know - it's possible you may need to open a new PR for it to be counted.

**Comment by JacksonBates** [comment]
Edit: actually, I just needed to run sass on the folder to get it to work

**Comment by JacksonBates** [comment]
This looks good - If you can confirm you get your hacktoberfest credit I'll merge it, or wait for a new PR

**Comment by oxavibes** [comment]
Hi, I just checked and it does not count it I think I have to create a new PR

**Pull request closed without merging**
